#!/bin/sh
set -eu
if [ "$1" = configure ]; then
    version=7.2.0-7-MANJARO-ARM
    payload=/usr/lib/linux-image-h728-manjaro
    depmod "$version"
    mkdir -p /boot/dtb/allwinner
    cp "$payload/Image" "/boot/vmlinuz-$version"
    cp "$payload/Image" /boot/Image
    cp "$payload/config" "/boot/config-$version"
    cp "$payload/sun55i-h728-x96qpro+.dtb" /boot/dtb/allwinner/
    if [ -f "/boot/initrd.img-$version" ]; then
        update-initramfs -u -k "$version"
    else
        update-initramfs -c -k "$version"
    fi
fi
